steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/fireline:latest', '.']
  - name: 'us.gcr.io/$PROJECT_ID/fireline:latest'
    dir: '/app'
    args: ['yarn', 'ci:config']
  - name: 'us.gcr.io/$PROJECT_ID/fireline:latest'
    dir: '/app'
    args: ['yarn', 'ci:test']
  - name: 'us.gcr.io/$PROJECT_ID/fireline:latest'
    dir: '/app'
    args: ['yarn', 'ci:deploy']
images: ['us.gcr.io/$PROJECT_ID/fireline:latest']
options:
  env:
    - 'FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL'
    - 'FIREBASE_PROJECT=$_FIREBASE_PROJECT'
    - 'FIREBASE_TOKEN=$_FIREBASE_TOKEN'
    - 'GOOGLE_APPLICATION_CREDENTIALS=$_GOOGLE_APPLICATION_CREDENTIALS'
    - 'SERVICE_ACCOUNT_BASE64=$_SERVICE_ACCOUNT_BASE64'
    - 'STRIPE_PK=$_STRIPE_PK'
    - 'STRIPE_SK=$_STRIPE_SK'
    - 'STRIPE_SIGNING_SECRET_PRICE=$_STRIPE_SIGNING_SECRET_PRICE'
    - 'STRIPE_SIGNING_SECRET_PRODUCT=$_STRIPE_SIGNING_SECRET_PRODUCT'
    - 'STRIPE_SIGNING_SECRET_SUBSCRIPTION=$_STRIPE_SIGNING_SECRET_SUBSCRIPTION'
timeout: 3600s
